version: '3'
services:
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - localprom
    ports:
      - 9093:9093
networks:
  localprom:
    driver: bridge